version: '3.8'

services:
  # 后端API服务
  pc-guide-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pc-guide-backend
    restart: unless-stopped
    ports:
      - "9999:9999"
    environment:
      - NODE_ENV=production
      - PORT=9999
      # 数据库配置
      - DB_HOST=47.94.202.171
      - DB_PORT=3306
      - DB_NAME=cig
      - DB_USER=root
      - DB_PASSWORD=G547M!tv#APV77PBjz=~
      # JWT配置
      - JWT_SECRET=xlcig_装机指南_jwt_secret_key_2024
      - JWT_EXPIRES_IN=7d
      # CORS配置 - 允许api子域名
      - CORS_ORIGIN=https://api.xlcig.cn,https://xlcig.cn,https://www.xlcig.cn,http://api.xlcig.cn,http://xlcig.cn,http://www.xlcig.cn
      # OSS配置
      - OSS_ACCESS_KEY_ID=LTAI5tP4EhrWG2BADv5yWgtq
      - OSS_ACCESS_KEY_SECRET=ujiUEg4RCATJ3ZQNa1s7IdNrQBYaxI
      - OSS_BUCKET=xlcig
      - OSS_REGION=oss-cn-beijing
      - OSS_ENDPOINT=https://oss-cn-beijing.aliyuncs.com
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9999/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: pc-guide-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - ./error-pages:/usr/share/nginx/html/error:ro
      # SSL证书挂载点（如果有证书的话）
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - pc-guide-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-logs:
    driver: local 