// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/7/4 22:26:32
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/codeGitee/xlcig-web/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlcig-web/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlcig-web/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlcig-web/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlcig-web/frontend/plugins/**/*.{js,ts,mjs}","D:/codeGitee/xlcig-web/frontend/composables/**/*.{js,ts,mjs}","D:/codeGitee/xlcig-web/frontend/utils/**/*.{js,ts,mjs}","D:/codeGitee/xlcig-web/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlcig-web/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlcig-web/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlcig-web/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;