// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/7/5 21:03:10
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/codeGitee/xlweb/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlweb/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlweb/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlweb/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlweb/plugins/**/*.{js,ts,mjs}","D:/codeGitee/xlweb/composables/**/*.{js,ts,mjs}","D:/codeGitee/xlweb/utils/**/*.{js,ts,mjs}","D:/codeGitee/xlweb/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlweb/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlweb/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/codeGitee/xlweb/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;