// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/7/10 02:48:15
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/code/xlweb/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/code/xlweb/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/code/xlweb/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/code/xlweb/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/code/xlweb/plugins/**/*.{js,ts,mjs}","D:/code/xlweb/composables/**/*.{js,ts,mjs}","D:/code/xlweb/utils/**/*.{js,ts,mjs}","D:/code/xlweb/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/code/xlweb/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/code/xlweb/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/code/xlweb/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;